name: simple_dart_web_showcase
description: simple dart web showcase
version: 0.0.4
publish_to: none

platforms:
  web:


environment:
  sdk: '^2.16.0'

dependencies:
  simple_dart_web_views: '0.0.4'
  simple_dart_web_widgets: '0.0.4'

dev_dependencies:
  build_runner: ^2.1.11
  build_web_compilers:
