name: simple_dart_web_showcase
description: simple dart web showcase
version: 0.0.1
publish_to: none

environment:
  sdk: '^2.13.4'

dependencies:
  simple_dart_web_views:
    git: https://github.com/ViktorZahar/simple_dart_web_views.git
  #    path: ../simple_dart_web_views

  simple_dart_web_widgets:
    git: https://github.com/ViktorZahar/simple_dart_web_widgets.git
  #    path: ../simple_dart_web_widgets

dev_dependencies:
  build_runner: ^2.0.5
  build_web_compilers:
